/**
 * Friendly display names for the most commonly traded tickers.
 * For tickers not in this map, just the symbol is shown.
 */

export const TICKER_DISPLAY_NAMES: Record<string, string> = {
  // ── Index ETFs ──
  SPY: "S&P 500 ETF",
  QQQ: "Nasdaq 100 ETF",
  IWM: "Russell 2000 ETF",
  DIA: "Dow Jones ETF",
  // ── Sector ETFs ──
  XLF: "Financials ETF",
  XLE: "Energy ETF",
  XLK: "Technology ETF",
  XBI: "Biotech ETF",
  ARKK: "ARK Innovation ETF",
  GLD: "Gold ETF",
  SLV: "Silver ETF",
  TLT: "20+ Yr Treasury ETF",
  EEM: "Emerging Markets ETF",
  EFA: "EAFE ETF",
  VXX: "VIX Short-Term Futures",
  HYG: "High Yield Bond ETF",
  USO: "Oil ETF",
  SMH: "Semiconductor ETF",
  XLP: "Consumer Staples ETF",
  XLV: "Healthcare ETF",
  XLI: "Industrials ETF",
  XLU: "Utilities ETF",
  KWEB: "China Internet ETF",
  // ── Mega-Cap Tech ──
  AAPL: "Apple",
  MSFT: "Microsoft",
  AMZN: "Amazon",
  GOOGL: "Alphabet (Google)",
  GOOG: "Alphabet (Class C)",
  META: "Meta Platforms",
  NVDA: "Nvidia",
  TSLA: "Tesla",
  // ── Semiconductors ──
  AMD: "AMD",
  INTC: "Intel",
  AVGO: "Broadcom",
  MU: "Micron",
  QCOM: "Qualcomm",
  TSM: "TSMC",
  MRVL: "Marvell",
  ARM: "ARM Holdings",
  // ── Other Large Cap ──
  NFLX: "Netflix",
  CRM: "Salesforce",
  ORCL: "Oracle",
  ADBE: "Adobe",
  COST: "Costco",
  WMT: "Walmart",
  JPM: "JPMorgan Chase",
  BAC: "Bank of America",
  GS: "Goldman Sachs",
  V: "Visa",
  MA: "Mastercard",
  UNH: "UnitedHealth",
  JNJ: "Johnson & Johnson",
  PFE: "Pfizer",
  XOM: "Exxon Mobil",
  CVX: "Chevron",
  BA: "Boeing",
  DIS: "Disney",
  NKE: "Nike",
  SBUX: "Starbucks",
  HD: "Home Depot",
  LOW: "Lowe's",
  CAT: "Caterpillar",
  DE: "Deere & Co",
  PYPL: "PayPal",
  SQ: "Block (Square)",
  SHOP: "Shopify",
  COIN: "Coinbase",
  HOOD: "Robinhood",
  SOFI: "SoFi",
  PLTR: "Palantir",
  SNAP: "Snap",
  UBER: "Uber",
  LYFT: "Lyft",
  RIVN: "Rivian",
  LCID: "Lucid Motors",
  NIO: "NIO",
  LI: "Li Auto",
  BABA: "Alibaba",
  JD: "JD.com",
  PDD: "PDD Holdings",
  ABNB: "Airbnb",
  DASH: "DoorDash",
  RBLX: "Roblox",
  ROKU: "Roku",
  ZM: "Zoom",
  CRWD: "CrowdStrike",
  PANW: "Palo Alto Networks",
  NET: "Cloudflare",
  DKNG: "DraftKings",
  MARA: "Marathon Digital",
  RIOT: "Riot Platforms",
  SMCI: "Super Micro Computer",
};

/** Get display label for a ticker: "AAPL — Apple" or just "AAPL" */
export function getTickerLabel(ticker: string): string {
  const name = TICKER_DISPLAY_NAMES[ticker];
  return name ? `${ticker} — ${name}` : ticker;
}
